[package]
name = "ip-changed-telegram-message"
description = "Send a telegram message when the public ip changes"
version = "0.4.0"
license = "MIT"
repository = "https://github.com/EdJoPaTo/ip-changed-telegram-message"
authors = ["EdJoPaTo <ip-changed-telegram-message-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# See https://doc.rust-lang.org/rustc/codegen-options/index.html
codegen-units = 1
lto = true

[dependencies]
anyhow = "1"
log = "0.4"
pretty_env_logger = "0.4"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls"]

[dependencies.teloxide]
#version = "0.4"
# Wait for next release which includes PR 354. See https://github.com/teloxide/teloxide/issues/364
git = "https://github.com/teloxide/teloxide"
branch = "dev"
default-features = false
features = ["rustls"]

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread", "macros"]
